@startuml

package Core {
    class Game {

    }

    class InputHandler {

    }

    class SceneHandler {

    }

    class Renderer {

    }

    class Texture {

    }

    class Event {

    }

    class KeyboardEvent {

    }

    abstract class Renderable {
        +void createFromPath(string, SDL_Renderer)
        +void setSprite(Texture*)
        +void setRenderId(int)
        +int getRenderId(int)
        +Texture* getTexture()
        +SDL_Texture* getSDLTexture()
        +SDL_Rect* getRenderRect()
        +void render(SDL_Rect*)

        #int renderId
        #Texture* image
    }

    class AnimatedSprite {
        +void render(SDL_Rect*)
        #SDL_Rect currentFrame
        #int frameCount
        #bool cyclic
        #bool loops
    }

    class Entity {

    }

    class Scene {

    }

    abstract class EventHandler {

    }
}

Renderable <|-- AnimatedSprite

Game --> InputHandler
Game --> SceneHandler
Game --> Renderer

Renderer --> Renderable

Renderable --> Texture

SceneHandler o-- Scene

EventHandler <|- Scene

EventHandler --> Event

Event <|.. KeyboardEvent
Scene o-- Entity

@enduml